name: geoclue
description: "GeoClue: The Geolocation Service"
homepage: https://gitlab.freedesktop.org/geoclue/geoclue/-/wikis/home
repository: https://github.com/canonical/geoclue.dart
issue_tracker: https://github.com/canonical/geoclue.dart/issues
version: 0.1.0

environment:
  sdk: '>=2.16.0 <3.0.0'

platforms:
  linux:

dependencies:
  dbus: ^0.7.3
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.1.8
  lints: ^1.0.0
  mockito: 5.3.2
  test: ^1.16.0
